# -*- coding: utf-8 -*-
"""Food_Vision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cGDKYt5fbDlCyyJGsALzn-aXh9qoKrGc
"""

# Download helper functions script
!wget https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py

# Import helper functions
from helper_functions import create_tensorboard_callback, plot_loss_curves, compare_historys

# Import the model we made before
!wget https://storage.googleapis.com/ztm_tf_course/food_vision/07_efficientnetb0_feature_extract_model_mixed_precision.zip

# Unzip the model downloaded
!mkdir downloaded_gs_model
!unzip 07_efficientnetb0_feature_extract_model_mixed_precision.zip -d downloaded_gs_model

# Get TensorFlow datasets
import tensorflow_datasets as tfds

# List all available datasets
datasets_list = tfds.list_builders() # get all available datasets in TFDS
print("food101" in datasets_list)

# Load in the data
(train_data, test_data), ds_info = tfds.load(name = "food101",
                                             split = ["train", "validation"],
                                             batch_size = 32,
                                             shuffle_files = True,
                                             as_supervised = True,
                                             with_info = True)

# Load in the model
import tensorflow as tf
food_vision = tf.keras.models.load_model("/content/downloaded_gs_model/07_efficientnetb0_feature_extract_model_mixed_precision")

food_vision.summary()

# Evaluate our model on all of the test data
food_vision.evaluate(test_data)

# Make all the layers in the base model trainable
for layer in food_vision.layers[1].layers:
  layer.trainable = True
  print(layer.name, layer.trainable, layer.dtype_policy)

tf.keras.mixed_precision.set_global_policy("mixed_float16")

tf.keras.mixed_precision.global_policy()

# Creating an EarlyStopping callback
early_stopping = tf.keras.callbacks.EarlyStopping(monitor = "val_loss", patience = 3)

# Creating a model checkpoint callback
ckpt_path = "model_checkpoints/cp.ckpt"
checkpoint = tf.keras.callbacks.ModelCheckpoint(ckpt_path,
                                                monitor = "val_loss",
                                                save_best_only = True,
                                                save_weights_only = True)

# Check what datatype are our labels
ds_info.features["label"]

# Compile food vision model
food_vision.compile(loss = "sparse_categorical_crossentropy",
                    optimizer = tf.keras.optimizers.Adam(learning_rate = 0.0001),
                    metrics = ["accuracy"])

# Fit our model
history = food_vision.fit(train_data,
                          epochs = 100,
                          steps_per_epoch = len(train_data),
                          validation_data = test_data,
                          validation_steps = int(0.15 * len(test_data)),
                          callbacks = [early_stopping, checkpoint])

train_data

plot_loss_curves(history)

